### ISSUE TITLE
global ignore/exclude

### ISSUE THREAD

**Issue by quinn-dougherty** [numtide/treefmt-nix#171]
**Is your feature request related to a problem? Please describe.**

I'm working with git submodules, and they currently feel incompatible with `treefmt-nix`. 

**Describe the solution you'd like**

`treefmt.config.settings.exclude = [ "dir1" "dir2" ]`

**Describe alternatives you've considered**
```nix
settings.formatter = {
        prettier.excludes = [ "submoduleA/" ];
        black.excludes = [ "submoduleA/" ];
      };
```
this did not work.

**Comment by zimbatm** [comment]
try `treefmt.config.settings.global.exclude = [ "dir1" "dir2" ]`

**Comment by zimbatm** [comment]
assuming it's fixed

**Comment by SebTM** [comment]
Works for me but for anyone else searching: `folder/**` is the required format (at least for me excluding a submodule recursive) - also the option appears to be called `excludes` not `exclude` and for me it does not throw an error just ignores the (invalid?) option ✌🏻
