### ISSUE TITLE
remove old deprecation warning for ruff

### ISSUE THREAD

**Issue by phanirithvij** [numtide/treefmt-nix#211]
**Describe the bug**

I keep seeing the warning `programs.ruff.enable has been renamed to programs.ruff.check`

But the thing is I am not even using ruff in my treefmt config.

**To Reproduce**

Not sure, whenever I am doing `nixos-rebuild` or `home-manager switch` I get it sometimes, but not when using `treefmt-nix` via `nix fmt`

**Expected behavior**

If I am not using it, it shouldn't warn me.

**System information**

```
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.44, NixOS, 24.11 (Vicuna), 24.11.20240806.8e27e75`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/whdnxrs6vh9wv72fvkp4622wsl36x6xx-source`
```

**Additional context**

Maybe just disable that in ruff.nix as a temporary fix. since it has been [a while](https://github.com/numtide/treefmt-nix/commit/c6aaf729f34a36c445618580a9f95a48f5e4e03f) since the users were warned about it.

**Comment by zimbatm** [comment]
I'm not able to reproduce locally. Can you share the code?

**Comment by phanirithvij** [comment]
I was able to reproduce the issue consistently, but since the last flake update I did (nixos-unstable), I can't anymore. Previously, I saw a yellow warning `trace` with most nix commands in my system flake. I'm using direnv and nix-output-monitor, as well so the bug might not be from treefmt/treefmt-nix.

I think #212 is a good fix for now. Sorry, I don't have time to revert my system to reproduce it, but I'll provide more details if it happens again.

**Comment by phanirithvij** [comment]
So I made a repo https://github.com/phanirithvij/nix-eval-bugreport, just do `nix develop` inside it and you should see the trace.

**Comment by phanirithvij** [comment]
So my guess is it is working as it is supposed to?
Just like how I get all the current traces defined in nixpkgs printed when doing nixos-rebuild for the very first evaluation?

So this is a non-issue but since I keep modifying my flake regularly I keep seeing this frequently.
Sorry, I guess this github issue can be closed and you may decide on whether or not to proceed with #212.

**Comment by zimbatm** [comment]
Thanks. This is surprising to me, too, so I will use your repo to investigate. I would expect the warning to only show up when the enable option is being used.

I also noticed that `nix flake check` currently has an eval error because of ruff not having an enable function, and not sure why CI didn't catch that.

**Comment by phanirithvij** [comment]
My guess is it is same as https://github.com/NixOS/nixpkgs/issues/306276

**Comment by zimbatm** [comment]
:+1: thanks, found the solution thanks to your repro
