### ISSUE TITLE
Add sqlfluff, sql formatter & linter for most dialects

### ISSUE THREAD

**Issue by o-az** [numtide/treefmt-nix#257]
**Is your feature request related to a problem? Please describe.**

feature request to add https://github.com/sqlfluff/sqlfluff

dialects currently supported by sqlfluff

ANSI SQL
SQL definition
[Athena](https://aws.amazon.com/athena/)
[BigQuery](https://cloud.google.com/bigquery/)
[ClickHouse](https://clickhouse.com/)
[Databricks](https://databricks.com/)
[Db2](https://www.ibm.com/analytics/db2)
[DuckDB](https://duckdb.org/)
[Exasol](https://www.exasol.com/)
[Greenplum](https://greenplum.org/)
[Hive](https://hive.apache.org/)
[Materialize](https://materialize.com/)
[MySQL](https://www.mysql.com/)
[Oracle](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/index.html)
[PostgreSQL](https://www.postgresql.org/)
[Redshift](https://docs.aws.amazon.com/redshift/index.html)
[Snowflake](https://www.snowflake.com/)
[SOQL](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql.htm)
[SparkSQL](https://spark.apache.org/docs/latest/)
[SQLite](https://www.sqlite.org/)
[StarRocks](https://www.starrocks.io/)
[Teradata](https://www.teradata.com/)
[Transact-SQL](https://docs.microsoft.com/en-us/sql/t-sql/language-reference) 
[Trino](https://trino.io/)
[Vertica](https://www.vertica.com/)

**Describe the solution you'd like**

to have sqlfluff as an options for linting and formatting

**Describe alternatives you've considered**

**Additional context**

**Comment by Mic92** [comment]
Is it in nixpkgs? If yes, just do a pull request.

**Comment by zimbatm** [comment]
Happy to get PRs for any formatter in nixpkgs that adheres to the [treefmt formatter spec](https://treefmt.com/latest/reference/formatter-spec/).

**Comment by o-az** [comment]
@zimbatm i'm working on a pr for sqlfluff. One question: how do you decide what goes into settings and what goes into options directly?

For example I'm looking at these two and how they use `include`:

https://github.com/numtide/treefmt-nix/blob/main/programs/dprint.nix#L60-L65

https://github.com/numtide/treefmt-nix/blob/main/programs/nixpkgs-fmt.nix#L12-L15

it looks like `settings` is what would be in the formatter's config file?

**Comment by zimbatm** [comment]
Looks good to me, once the CI passes.

I would say the rule of thumb is to use the options if the set of arguments is small (less than 10). Then shift to a config file with settings.

**Comment by o-az** [comment]
@zimbatm I checked the failure in CI and it seems it's something related to the README.md updates but not clear to me what is wrong. Any advice would be appreciated!

https://buildbot.numtide.com/#/builders/395/builds/144

https://buildbot.numtide.com/#/builders/314/builds/144

https://buildbot.numtide.com/#/builders/236/builds/147
