### ISSUE TITLE
eval error using flake-parts: attribute 'flake-parts-lib' missing

### ISSUE THREAD

**Issue by aidalgol** [numtide/treefmt-nix#271]
# Describe the bug
Trying to use `treefmt` via `flake-parts` produces an eval error.

# To Reproduce
1. Create an empty directory
2. Write the following `flake.nix` file.
   ```nix
   {
     inputs = {
       flake-parts.url = "github:hercules-ci/flake-parts";
       treefmt-nix.url = "github:numtide/treefmt-nix";
       nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
     };
     outputs =
       {
         flake-parts,
         nixpkgs,
         ...
       }@inputs:
       flake-parts.lib.mkFlake { inherit inputs; } {
         systems = [ "x86_64-linux" ];
         perSystem =
           {
             config,
             self',
             inputs',
             pkgs,
             system,
             ...
           }:
           {
             imports = [
               inputs.treefmt-nix.flakeModule
             ];
   
             treefmt = {
               projectRootFile = "flake.nix";
               programs.nixfmt-rfc-style.enable = true;
             };
           };
         flake = { };
       };
   }
   ```
3. Run `nix flake lock`
4. Run `nix fmt`

```console
error:
… while calling the 'head' builtin
at /nix/store/f9zgiyh2mhgqrrbbmbn3cwcjhbn2fzf6-source/attrsets.nix:1575:11:
1574|         || pred here (elemAt values 1) (head values) then
1575|           head values
|           ^
1576|         else

… while evaluating the attribute 'value'
at /nix/store/f9zgiyh2mhgqrrbbmbn3cwcjhbn2fzf6-source/modules.nix:816:9:
815|     in warnDeprecation opt //
816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
|         ^
817|         inherit (res.defsFinal') highestPrio;

(stack trace truncated; use '--show-trace' to show the full trace)

error: attribute 'flake-parts-lib' missing
at /nix/store/f9zgiyh2mhgqrrbbmbn3cwcjhbn2fzf6-source/modules.nix:515:28:
514|         addErrorContext (context name)
515|           (args.${name} or config._module.args.${name})
|                            ^
516|       ) (functionArgs f);
```
(The full trace does not include any lines in `flake.nix`, so I have omitted it.)

# Expected behavior
`nix fmt` to run `treefmt`.

# System information
- system: `"x86_64-linux"`
- host os: `Linux 6.6.63, NixOS, 25.05 (Warbler), 25.05.20241128.970e93b`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Lix, like Nix) 2.91.1
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/aidan/.config/nix/nix.conf:/home/aidan/.config/kdedefaults/nix/nix.conf:/nix/store/w4r255xy5az98q5im6m7yzx5536qa8dy-plasma-workspace-6.2.4/etc/xdg/nix/nix.conf:/nix/store/b06v1z7pgfdcv6iix1mja9ych2yp6zw3-kglobalacceld-6.2.4/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/nix/store/w4r255xy5az98q5im6m7yzx5536qa8dy-plasma-workspace-6.2.4/etc/xdg/nix/nix.conf:/nix/store/b06v1z7pgfdcv6iix1mja9ych2yp6zw3-kglobalacceld-6.2.4/etc/xdg/nix/nix.conf:/nix/store/pdgsrs8i0crldkl8n2cp9jx3h06rcnzc-baloo-6.8.0/etc/xdg/nix/nix.conf:/home/aidan/.config/kdedefaults/nix/nix.conf:/etc/xdg/nix/nix.conf:/home/aidan/.nix-profile/etc/xdg/nix/nix.conf:/nix/profile/etc/xdg/nix/nix.conf:/home/aidan/.local/state/nix/profile/etc/xdg/nix/nix.conf:/etc/profiles/per-user/aidan/etc/xdg/nix/nix.conf:/nix/var/nix/profiles/default/etc/xdg/nix/nix.conf:/run/current-system/sw/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/icglv8lfkxzd7qkpxh3kawhnxbixg3mi-lix-2.91.1/share`
- nixpkgs: `/home/aidan/.nix-defexpr/channels/nixpkgs`

# Additional context

There is also a documentation bug here, #270, so I had to try working out how to use this from just the minimal example in the README.

**Comment by zimbatm** [comment]
Try moving the `imports` one level up. The issue is that the module is designed to be imported on the top-level instead of per system.

```diff
diff --git a/repro/flake.nix b/repro/flake.nix
index 3cc165a..114aceb 100644
--- a/repro/flake.nix
+++ b/repro/flake.nix
@@ -12,6 +12,11 @@
     }@inputs:
     flake-parts.lib.mkFlake { inherit inputs; } {
       systems = [ "x86_64-linux" ];
+
+      imports = [
+        inputs.treefmt-nix.flakeModule
+      ];
+
       perSystem =
         {
           config,
@@ -22,10 +27,6 @@
           ...
         }:
         {
-          imports = [
-            inputs.treefmt-nix.flakeModule
-          ];
-
           treefmt = {
             projectRootFile = "flake.nix";
             programs.nixfmt-rfc-style.enable = true;
```

**Comment by aidalgol** [comment]
Yep, that was the problem.  Thanks!
