### ISSUE TITLE
support TOML formatting via taplo 

### ISSUE THREAD

**Issue by steveej** [numtide/treefmt-nix#280]
**Is your feature request related to a problem? Please describe.**

i can't find any config options for a toml formatter.

**Describe the solution you'd like**

it would be nice to get support for that via [taplo](https://taplo.tamasfe.dev/)

**Describe alternatives you've considered**

enable the alpha-grade prettier toml plugin, which might result in the same amount of work and probably is less robust than taplo integration.

**Additional context**

i came across taplo in the [crane workspace guide](https://crane.dev/examples/quick-start-workspace.html) and then saw CI fail for that check :wink:

**Comment by zimbatm** [comment]
sounds good, PR welcome!

**Comment by poopsicles** [comment]
isn't `programs.taplo.enable = true;` in `treefmt.nix` already possible? it's mentioned in the readme

**Comment by zimbatm** [comment]
yes it looks like it's already available. see https://github.com/numtide/treefmt-nix/blob/main/programs/taplo.nix @steveej

**Comment by steveej** [comment]
great! and apologies for the oversight. i realize that i failed to enable it because i had copied a blueprint template that disabled toml formatting via `settings.global.excludes`.
