### ISSUE TITLE
error: attribute 'writeShellScriptBin' missing

### ISSUE THREAD

**Issue by teto** [numtide/treefmt-nix#30]
**Describe the bug**

In my flake, I tried to add a package with this code
```
		   treefmt-with-config = treefmt-nix.lib.mkWrapper nixpkgs {
			 # Used to find the project root
			 projectRootFile = ".git/config";
			 # Enable the terraform formatter
			 # programs.terraform.enable = true;
			 # Override the default package
			 # programs.terraform.package = nixpkgs.terraform_1_0;
			 # Override the default settings generated by the above option
			 # settings.formatter.terraform.excludes = ["hello.tf"];
		   };

```
but I got
```
error: attribute 'writeShellScriptBin' missing

       at /nix/store/z1wfgivqn358jnab22rj0qhacg0qmmdp-source/module-options.nix:92:17:

           91|           let
           92|             x = pkgs.writeShellScriptBin "treefmt" ''
             |                 ^
           93|               find_up() {
```

version of treefmt -nix `nix flake metadata`
treefmt-nix: github:numtide/treefmt-nix/c117283f7482b99a89de0d6ae4b77318ad283294

Sidequestion: why do i need to pass nixpkgs to `treefmt-nix.lib.mkWrapper`

**Comment by zimbatm** [comment]
Try replacing `nixpkgs` with `nixpkgs.legacyPackages.${system}`.

It's a way to defer the dependency on nixpkgs. That design choice is questionable :)

**Comment by teto** [comment]
> It's a way to defer the dependency on nixpkgs. That design choice is questionable :)

first time I see it in a flake. Guess it makes sense as long as "follows" is broken but still surprising :)

that fixed it thanks !
