### ISSUE TITLE
Expose each formatter as TOML config

### ISSUE THREAD

**Issue by zimbatm** [numtide/treefmt-nix#34]
**Is your feature request related to a problem? Please describe.**

The formatter snippets are currently only available to Nix users. It should be possible to re-export the data to TOML, so it's also valuable for the other users.

**Describe the solution you'd like**

Some Nix script that loads and enables each formatter module, captures the generated configuration TOML and then stores it somewhere. It should also clean the formatter command, so it doesn't point to the /nix/store entry. Just the basename is enough.

I'm not sure exactly where the generated TOML should end up in.

**Describe alternatives you've considered**

**Additional context**

**Comment by r-muhairi** [comment]
Perhaps a simple flake app that is run generating a `treefmt.toml` in the project root?
