### ISSUE TITLE
Add dprint formatter

### ISSUE THREAD

**Issue by adrian-gierakowski** [numtide/treefmt-nix#51]
I use [dprint](https://dprint.dev/) for TS/JS/JSON/Markdown. It’s really fast and configurable. 

Btw. dprint also supports running other formatters via [exec](https://dprint.dev/plugins/exec/), or pure wasm plugins, so there seems to be a bit of overlap between treefmt and dprint. Maybe there is a possibility for collaboration as it’s also written in rust.

**Comment by zimbatm** [comment]
Sounds good, as long as it adheres to the [treefmt formatter spec](https://numtide.github.io/treefmt/formatters-spec/), I don't mind having it added.
