### ISSUE TITLE
[flake-parts] Allow disabling the autowiring of flake check

### ISSUE THREAD

**Issue by srid** [numtide/treefmt-nix#63]
https://github.com/numtide/treefmt-nix/blob/b25d1a3c2c7554d0462ab1dfddf2f13128638b90/flake-module.nix#L36

When https://github.com/cachix/pre-commit-hooks.nix already adds a check (it includes a treefmt hook), the check added by treefmt is redundant and will just slow CI down unnecessarily.

An option in the flake-parts module to disable this check would be nice.

**Comment by zimbatm** [comment]
Makes sense, I would accept a PR
