### ISSUE TITLE
Add a spellchecker

### ISSUE THREAD

**Issue by KaiserKarel** [numtide/treefmt-nix#76]
**Is your feature request related to a problem? Please describe.**

Cspell or another spellchecker would be a valuable addition.

**Comment by zimbatm** [comment]
:+1: PR welcome

**Comment by zimbatm** [comment]
@KaiserKarel does this help? https://github.com/numtide/treefmt-nix/pull/95

**Comment by zimbatm** [comment]
yup, thanks
