### ISSUE TITLE
Thoughts on adding erlfmt?

### ISSUE THREAD

**Issue by yurrriq** [numtide/treefmt-nix#82]
**Is your feature request related to a problem? Please describe.**

https://github.com/WhatsApp/erlfmt

**Describe the solution you'd like**

If this is something, you'd consider, I'd be happy to prepare a PR.

**Describe alternatives you've considered**

:cricket::cricket:

**Additional context**

There are alternatives, such as https://github.com/AdRoll/rebar3_format

**Comment by zimbatm** [comment]
Sure, we accept all the formatters that follow the [treemft formatter specification](https://github.com/numtide/treefmt/blob/main/docs/formatters-spec.md)
